name: Run Tests on Changed Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      # Define the output variable FILES
      id: files
      # The value is the list of changed files
      value: ${{ steps.set-files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Update npm
        run: npm install -g npm@7.24.0

      - name: Install dependencies
        run: npm install --save-dev jest

      - name: Set commit range
        id: set-files
        run: echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' || true)"

      - name: Display changed files
        run: echo "${{ steps.set-files.outputs.files }}"

      - name: Set output variable
        id: output-files
        run: echo "files=${{ steps.set-files.outputs.files }}" 

      - name: Run Jest tests
        run: |
          source <(echo "${{ steps.output-files.outputs.files }}")
          echo "Changed files: $files"
          if [ -n "$files" ]; then
            ./node_modules/jest/bin/jest.js $files
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
