name: Run Tests on Changed Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Update npm
        run: npm install -g npm@7.24.0

      - name: Install dependencies
        run: npm install --save-dev jest

      - name: Set commit range in .env
        run: |
          echo "FILES=\$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' || true)" > .env

      - name: Debug Info
        run: |
          echo "Current Commit: ${{ github.sha
          echo "Previous Commit: ${{ github.event.before }}"
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' || true)
          echo "Changed Files: $files"
          echo "FILES=$files" >> $GITHUB_ENV

      - name: Source .env and process changed files
        run: |
          source .env
          if [ -n "$FILES" ]; then
            echo "Changed files: $FILES"
            # You can loop through the changed files if needed
            for file in $FILES; do
              echo "Processing file: $file"
              # Run any specific commands related to each changed file
            done
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
