name: CI

on:
  push:
    branches:
      - main

jobs:
  changed_files:
  runs-on: ubuntu-latest
  name: Test changed-files
  outputs:
    id: changed_files
    value: ${{ steps.changed-files.outputs.all_changed_files }}
  steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

run_tests:
  runs-on: ubuntu-latest
  name: Run tests
  needs: changed_files
  steps:
    - uses: actions/checkout@v4
    - name: Get changed files from previous job
      run: echo "FILES=${{ needs.changed_files.outputs.changed_files }}" >> $GITHUB_ENV
    - name: Display changed files
      run: echo "$FILES"
    - name: Run Jest tests
      run: |
        source $GITHUB_ENV
        if [ -n "$FILES" ]; then
          ./node_modules/jest/bin/jest.js $FILES
        else
          echo "No JavaScript files changed. Skipping tests."
        fi

