name: Run Tests on Changed Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Update npm
        run: npm install -g npm@7.24.0

      - name: Install dependencies
        run: |
          npm install --save-dev jest
          npm install

      - name: Debug Info
        run: |
          echo "Current Commit: ${{ github.sha }}"
          echo "Previous Commit: ${{ github.event.before }}"
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' || true)
          echo "Changed Files: $files"
          echo "FILES=$files" >> $GITHUB_ENV

      - name: Run tests on changed files
        run: |
          source .env
          if [ -n "$FILES" ]; then
            ./node_modules/jest/bin/jest.js $FILES
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
