name: Run Tests on Changed Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install --save-dev jest
          npm install

      - name: Determine changed files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' || true)"

      - name: Run tests on changed files
        run: |
          changed_files=$(echo "${{ steps.changed-files.outputs.files }}" | tr '\n' ' ')
          if [ -n "$changed_files" ]; then
            ./node_modules/jest/bin/jest.js $changed_files
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
