name: CI

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Find and list changed files
    outputs:
      id: changed_files
      value: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests on changed files
    needs: changed_files
    steps:
      - uses: actions/checkout@v4
      - name: Display changed files
        run: |
          echo "Changed files from the previous job: ${{ needs.changed_files.outputs.value }}"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - name: Install dependencies
        run: npm install --save-dev jest
      - name: Run Jest tests
        run: |
          changed_files="${{ needs.changed_files.outputs.value }}"
          if [ -n "$changed_files" ]; then
            ./node_modules/jest/bin/jest.js $changed_files
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
