name: CI

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.15.0'

      - name: Install dependencies
        run: npm install -g npm@8.5.5

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    needs: changed_files
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.15.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests based on changed files
        run: |
          source $GITHUB_ENV
          if [ -n "$FILES" ]; then
            ./node_modules/jest/bin/jest.js $FILES
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
