name: Run Tests on Changed Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set commit range and save to environment file
        run: echo "FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' || true)" >> $GITHUB_ENV

      - name: Display changed files
        run: echo "$FILES"

      - name: Run Jest tests
        run: |
          source $GITHUB_ENV
          echo "Changed files: $FILES"
          if [ -n "$FILES" ]; then
            ./node_modules/jest/bin/jest.js $FILES
          else
            echo "No JavaScript files changed. Skipping tests."
          fi
